repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/ruff-pre-commit
    rev: v0.19.3
    hooks:
      - id: ruff
        args: ["--fix", "--select", "E,F,W"]

  - repo: https://github.com/psf/black
    rev: 24.7.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.12

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]
